export const initialState = [
  {
    id: 1,
    title: "Notebook",
    category: "Electronics",
    quantity: 20,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/notebook/400/400",
  },
  {
    id: 2,
    title: "Smartphone",
    category: "Electronics",
    quantity: 15,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/smartphone/400/400",
  },
  {
    id: 3,
    title: "Headphones",
    category: "Accessories",
    quantity: 30,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/headphones/400/400",
  },
  {
    id: 4,
    title: "Backpack",
    category: "Fashion",
    quantity: 25,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/backpack/400/400",
  },
  {
    id: 5,
    title: "Water Bottle",
    category: "Lifestyle",
    quantity: 50,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/bottle/400/400",
  },
  {
    id: 6,
    title: "Keyboard",
    category: "Electronics",
    quantity: 18,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/keyboard/400/400",
  },
  {
    id: 7,
    title: "Mouse",
    category: "Electronics",
    quantity: 22,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/mouse/400/400",
  },
  {
    id: 8,
    title: "Desk Lamp",
    category: "Home",
    quantity: 12,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/lamp/400/400",
  },
  {
    id: 9,
    title: "Chair",
    category: "Furniture",
    quantity: 8,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/chair/400/400",
  },
  {
    id: 10,
    title: "Coffee Mug",
    category: "Kitchen",
    quantity: 40,
    price: 2000,
    imageUrl: "https://picsum.photos/seed/mug/400/400",
  },
];
